name: Run Python Script Every Hour

on:
  schedule:
    - cron: "0 * * * *"  # Runs at the start of every hour
  workflow_dispatch:    # Allows manual trigger as well

jobs:
  run-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create service account file
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$GOOGLE_SERVICE_ACCOUNT_JSON" > service_account.json

      - name: Run Python script
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          SESSIONS_TABLE: ${{ secrets.SESSIONS_TABLE }}
          CURATION_STATUS_TABLE: ${{ secrets.CURATION_STATUS_TABLE }}
          SPEAKERS_TABLE: ${{ secrets.SPEAKERS_TABLE }}
          GOOGLE_PRESENTATION_ID: ${{ secrets.GOOGLE_PRESENTATION_ID }}
          TEMPLATE_SLIDE_ID: ${{ secrets.TEMPLATE_SLIDE_ID }}
          GOOGLE_SERVICE_ACCOUNT_FILE: service_account.json
        run: python job.py
